### ISSUE TITLE
2023 Season To-Do List

### ISSUE THREAD

**Issue by KanhaKorgaonkar** [KanhaKorgaonkar/KanhaKorgaonkar#1]
- [ ] :auto_rickshaw: Attend an in-person hackathon
- [ ] :art: Become an expert at Jamstack
- [ ] :rocket: Learn web3 and build at least 5 hacks in web3
- [ ] :lab_coat: Host an in-person hackathon
- [ ] :bagel: Work on my side-project
- [ ] :chart_with_upwards_trend: Grow my community
